echo "gh auth login" 
echo "gh repo create blackbird-internship" 
echo "npx create-react-app blackbird" 
echo "cd <app-name>" 
echo "git checkout -b update_logo" 
echo "cp <path-to-downloaded-logo> src/logo.svg" 
echo "sed -i 's|https://www.example.com|https://www.propelleraero.com/dirtmate/|g' src/App.js" 
echo "git add ." 
echo "git commit -m \"Update logo and link\"" 
echo "git push origin update_logo" 
echo "gh pr create --base master --head update_logo --title \"Update logo and link\"" 
echo "gh pr merge <pull-request-number> --auto" 
